/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Control;

import Database_Handler.Queries;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author faith
 */
public class MainPage extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setIcon();
        SetDefaultSize();
        CenterOnScreen(this, true);
        CenterOnScreen(readMeDialog, true);
        Queries Load=new Queries();
        Load.GetAllActivities(AllActivity_Table);
        Queries Starred=new Queries();
        Starred.GetStarredActivities(Starred_Activities);
       
        
        AM.setSelected(true);
        SaveBtn.setEnabled(false);
        ((JTextComponent)ActivityDate.getDateEditor().getUiComponent()).setEditable(false);
        DeleteBtn.setEnabled(false);
        starActivityBtn.setEnabled(false);
        editActivityBtn.setEnabled(false);
        removeFromStarredBtn.setEnabled(false);
        editAct.setEnabled(false);
        
        hideTablesColumns();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        readMeDialog = new javax.swing.JDialog();
        jLabel43 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ParentPanel = new javax.swing.JPanel();
        AddNew_Page = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        AddNewPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        MyActivityPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllActivity_Table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        editActivityBtn = new javax.swing.JButton();
        starActivityBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        searchField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        EnterActivity_Page = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        IdLbl = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ActivityDate = new com.toedter.calendar.JDateChooser();
        ActivityName = new javax.swing.JTextField();
        ActivityVenue = new javax.swing.JTextField();
        ActivityMin = new javax.swing.JTextField();
        ActivityHr = new javax.swing.JTextField();
        PM = new javax.swing.JCheckBox();
        AM = new javax.swing.JCheckBox();
        SaveBtn = new javax.swing.JButton();
        Star = new javax.swing.JRadioButton();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel17 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        NoTime = new javax.swing.JCheckBox();
        NoVenue = new javax.swing.JCheckBox();
        clearBtn = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        Starred_Activites_Page = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        searchField2 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        editAct = new javax.swing.JButton();
        StarAct = new javax.swing.JButton();
        removeFromStarredBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Starred_Activities = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();

        readMeDialog.setTitle("Read me");
        readMeDialog.setResizable(false);

        jLabel43.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("A simple Event tracker software to help you keep track of  all  past, present  and 'yet to come' activities");

        jPanel7.setBackground(new java.awt.Color(0, 102, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("READ ME");
        jPanel7.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 180, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel40.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 51, 153));
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_Section.png"))); // NOI18N

        jLabel49.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 51, 153));
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/goHome.png"))); // NOI18N
        jLabel49.setText("Click to go back to home screen");

        jLabel54.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(0, 51, 153));
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pencil.png"))); // NOI18N
        jLabel54.setText("to edit your activity");

        jLabel53.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(0, 51, 153));
        jLabel53.setText("You can aslo search by date(year, month or day), venue or time");

        jLabel50.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 51, 153));
        jLabel50.setText("To view all your activities click on ");

        jLabel48.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(102, 102, 102));
        jLabel48.setText("Enter all required information click on SAVE button to save it");

        jLabel56.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 51, 153));
        jLabel56.setText("Click on");

        jLabel52.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(0, 51, 153));
        jLabel52.setText("Search for activity by entring a letter in the search field to filter it out as show above");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(204, 0, 0));
        jLabel41.setText("NB: You can hover your mouse on elements to see more tips");

        jLabel51.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(0, 51, 153));
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Views.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 51, 153));
        jLabel39.setText("Click on");

        jLabel55.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(0, 51, 153));
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trash.png"))); // NOI18N
        jLabel55.setText("remove activity");

        jLabel38.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 51, 153));
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star 1.png"))); // NOI18N
        jLabel38.setText("Click on this button to seperate your activities by adding to starred");

        jLabel37.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 51, 153));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add_Button.png"))); // NOI18N
        jLabel37.setText("Click on the Add new Activity button to enter your activity info to save");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel40)
                            .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addGap(30, 30, 30)
                .addComponent(jLabel38)
                .addGap(18, 18, 18)
                .addComponent(jLabel49)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel54))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel55))
                .addGap(18, 18, 18)
                .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout readMeDialogLayout = new javax.swing.GroupLayout(readMeDialog.getContentPane());
        readMeDialog.getContentPane().setLayout(readMeDialogLayout);
        readMeDialogLayout.setHorizontalGroup(
            readMeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(readMeDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        readMeDialogLayout.setVerticalGroup(
            readMeDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readMeDialogLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Activity Tracker");
        setResizable(false);

        ParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ParentPanel.setLayout(new java.awt.CardLayout());

        AddNew_Page.setBackground(new java.awt.Color(255, 255, 255));
        AddNew_Page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ACTIVITY TRACKER");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 750, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Track all your activities");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 750, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Activity_Tracker_Icon.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, 190));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Read me");
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, 30));

        AddNew_Page.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 300));

        AddNewPanel.setBackground(new java.awt.Color(51, 51, 255));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NEW.png"))); // NOI18N
        jLabel4.setText("ADD NEW ACTIVITY");
        jLabel4.setToolTipText("Enter new activity");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout AddNewPanelLayout = new javax.swing.GroupLayout(AddNewPanel);
        AddNewPanel.setLayout(AddNewPanelLayout);
        AddNewPanelLayout.setHorizontalGroup(
            AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        AddNewPanelLayout.setVerticalGroup(
            AddNewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        AddNew_Page.add(AddNewPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 330, 80));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star 2.png"))); // NOI18N
        jButton1.setToolTipText("Click to view Starred activites");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        AddNew_Page.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 40, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Views.png"))); // NOI18N
        jButton2.setToolTipText("Click to view all my Acivities");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AddNew_Page.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 40, 30));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 153));
        jLabel26.setText("2. Seperate your important activities");
        AddNew_Page.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 310, 20));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 153));
        jLabel28.setText("1. Add activities");
        AddNew_Page.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 200, 30));

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 153));
        jLabel29.setText("4. Search for activities and remove activities");
        AddNew_Page.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 320, 20));

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 51, 153));
        jLabel30.setText("3. Edit added activities");
        AddNew_Page.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 250, 30));

        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Created and powered by: Faithtotwer media-teck                          Copyright@2018                                     faithtowermediateck@gmail.com");
        AddNew_Page.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 680, 20));

        ParentPanel.add(AddNew_Page, "card2");

        MyActivityPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ACTIVITY TRACKER");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 490, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Track all your activities");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 490, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Activity_Tracker_Icon.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 180));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ALL MY ACTIVITIES");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 370, 60));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Read me");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 150, 80, -1));

        AllActivity_Table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AllActivity_Table.setForeground(new java.awt.Color(0, 0, 102));
        AllActivity_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        AllActivity_Table.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        AllActivity_Table.setFillsViewportHeight(true);
        AllActivity_Table.setGridColor(new java.awt.Color(255, 255, 255));
        AllActivity_Table.setRowHeight(30);
        AllActivity_Table.setRowMargin(10);
        AllActivity_Table.setSelectionBackground(new java.awt.Color(204, 204, 204));
        AllActivity_Table.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        AllActivity_Table.setShowHorizontalLines(false);
        AllActivity_Table.setShowVerticalLines(false);
        AllActivity_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllActivity_TableMouseClicked(evt);
            }
        });
        AllActivity_Table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AllActivity_TableKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(AllActivity_Table);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home 1.png"))); // NOI18N
        jButton3.setToolTipText("Go to home screen");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        editActivityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pencil.png"))); // NOI18N
        editActivityBtn.setToolTipText("Edit Activity");
        editActivityBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editActivityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActivityBtnActionPerformed(evt);
            }
        });

        starActivityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star 1.png"))); // NOI18N
        starActivityBtn.setToolTipText("Add to starred");
        starActivityBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        starActivityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starActivityBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trash.png"))); // NOI18N
        DeleteBtn.setToolTipText("Remove activity");
        DeleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        jButton7.setToolTipText("Add new Activities");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        searchField1.setToolTipText("Enter Activity to search");
        searchField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchField1KeyReleased(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search 1.png"))); // NOI18N
        jButton8.setToolTipText("Search for activities");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(51, 51, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star 2.png"))); // NOI18N
        jButton13.setToolTipText("Click to view Starred activites");
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel32.setForeground(new java.awt.Color(102, 102, 102));
        jLabel32.setText("Created and powered by: Faithtotwer media-teck                          Copyright@2018                                     faithtowermediateck@gmail.com");

        javax.swing.GroupLayout MyActivityPanelLayout = new javax.swing.GroupLayout(MyActivityPanel);
        MyActivityPanel.setLayout(MyActivityPanelLayout);
        MyActivityPanelLayout.setHorizontalGroup(
            MyActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MyActivityPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MyActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MyActivityPanelLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(editActivityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(starActivityBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        MyActivityPanelLayout.setVerticalGroup(
            MyActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MyActivityPanelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(MyActivityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(searchField1)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editActivityBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(starActivityBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        ParentPanel.add(MyActivityPanel, "card3");

        EnterActivity_Page.setBackground(new java.awt.Color(255, 255, 255));
        EnterActivity_Page.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ACTIVITY TRACKER");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 490, -1));

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Track all your activities");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 490, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Activity_Tracker_Icon.png"))); // NOI18N
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 180));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ADD NEW ACTIVITY");
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 370, 60));

        IdLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel5.add(IdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 10, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Read me");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 150, 80, -1));

        EnterActivity_Page.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 210));

        jLabel13.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel13.setText("ACTIVITY NAME");
        EnterActivity_Page.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 170, 35));

        jLabel14.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel14.setText("VENUE/PLACE");
        EnterActivity_Page.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 160, 35));

        jLabel15.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel15.setText("DATE OF ACTIVITY");
        EnterActivity_Page.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, 35));

        jLabel16.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel16.setText("SET TIME");
        EnterActivity_Page.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 160, 35));

        ActivityDate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
        ActivityDate.setDateFormatString(" yyyy-M-d");
        ActivityDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ActivityDateMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ActivityDateMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ActivityDateMouseReleased(evt);
            }
        });
        ActivityDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                ActivityDatePropertyChange(evt);
            }
        });
        ActivityDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ActivityDateKeyReleased(evt);
            }
        });
        EnterActivity_Page.add(ActivityDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 230, 35));

        ActivityName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ActivityName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        ActivityName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ActivityNameKeyReleased(evt);
            }
        });
        EnterActivity_Page.add(ActivityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 500, 35));

        ActivityVenue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ActivityVenue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        ActivityVenue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ActivityVenueKeyReleased(evt);
            }
        });
        EnterActivity_Page.add(ActivityVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 330, 40));

        ActivityMin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ActivityMin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActivityMin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        ActivityMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ActivityMinKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ActivityMinKeyTyped(evt);
            }
        });
        EnterActivity_Page.add(ActivityMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 70, 40));

        ActivityHr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ActivityHr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActivityHr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        ActivityHr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ActivityHrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ActivityHrKeyTyped(evt);
            }
        });
        EnterActivity_Page.add(ActivityHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 70, 40));

        PM.setText("PM");
        PM.setToolTipText("PM");
        PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(PM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 50, -1));

        AM.setText("AM");
        AM.setToolTipText("AM");
        AM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(AM, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 50, -1));

        SaveBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SaveBtn.setText("SAVE");
        SaveBtn.setToolTipText("Click to save your activities");
        SaveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 220, 40));

        Star.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        Star.setForeground(new java.awt.Color(255, 0, 0));
        Star.setText("Add to starred activities");
        EnterActivity_Page.add(Star, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 190, 30));

        jCalendar1.setToolTipText("Displays current date");
        EnterActivity_Page.add(jCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 230, 140));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star 1.png"))); // NOI18N
        EnterActivity_Page.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 30, 30));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home 1.png"))); // NOI18N
        jButton11.setToolTipText("Go to Home Screen");
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, 30));

        jButton10.setBackground(new java.awt.Color(51, 51, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Views.png"))); // NOI18N
        jButton10.setToolTipText("Click to view all my Acivities");
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 50, 30));

        jButton12.setBackground(new java.awt.Color(51, 51, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star 2.png"))); // NOI18N
        jButton12.setToolTipText("Click to view Starred activites");
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 50, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Current Date");
        EnterActivity_Page.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 200, 20));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("Enter all your activity details");
        EnterActivity_Page.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 214, 280, 40));

        NoTime.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NoTime.setText("Does not require time");
        NoTime.setToolTipText("This activity does not require time so ignore");
        NoTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoTimeActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(NoTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 150, -1));

        NoVenue.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        NoVenue.setText("Does not require venue ");
        NoVenue.setToolTipText("This activity does not require venue so ignore");
        NoVenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoVenueActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(NoVenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 160, -1));

        clearBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clearBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cross.png"))); // NOI18N
        clearBtn.setText("CLEAR");
        clearBtn.setToolTipText("Clear all fields");
        clearBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        EnterActivity_Page.add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 110, 40));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 153, 153));
        jLabel24.setText("30");
        EnterActivity_Page.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 30, 30));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 153, 153));
        jLabel25.setText("Eg.          12");
        EnterActivity_Page.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 90, 30));

        jLabel33.setForeground(new java.awt.Color(102, 102, 102));
        jLabel33.setText("Created and powered by: Faithtotwer media-teck                          Copyright@2018                                     faithtowermediateck@gmail.com");
        EnterActivity_Page.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 710, 20));

        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EnterActivity_Page.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 140, 30));

        ParentPanel.add(EnterActivity_Page, "card4");

        Starred_Activites_Page.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(0, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("ACTIVITY TRACKER");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 490, -1));

        jLabel21.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 204));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Track all your activities");
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 490, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Activity_Tracker_Icon.png"))); // NOI18N
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 200, 180));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("STARRED ACTIVITIES");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 370, 60));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Read me");
        jButton5.setToolTipText("Read tips");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 150, 80, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Home 1.png"))); // NOI18N
        jButton14.setToolTipText("Go to home screen");
        jButton14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        jButton15.setToolTipText("Add new activity");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(51, 51, 255));
        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Views.png"))); // NOI18N
        jButton16.setToolTipText("Click to view all my activites");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        searchField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchField2KeyReleased(evt);
            }
        });

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search 1.png"))); // NOI18N

        editAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pencil.png"))); // NOI18N
        editAct.setToolTipText("Edit activity");
        editAct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActActionPerformed(evt);
            }
        });

        StarAct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Star 1.png"))); // NOI18N
        StarAct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StarAct.setEnabled(false);

        removeFromStarredBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trash.png"))); // NOI18N
        removeFromStarredBtn.setToolTipText("Remove from starred");
        removeFromStarredBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        removeFromStarredBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFromStarredBtnActionPerformed(evt);
            }
        });

        Starred_Activities.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Starred_Activities.setForeground(new java.awt.Color(0, 102, 102));
        Starred_Activities.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Starred_Activities.setToolTipText("Important activities");
        Starred_Activities.setDropMode(javax.swing.DropMode.INSERT_ROWS);
        Starred_Activities.setFillsViewportHeight(true);
        Starred_Activities.setGridColor(new java.awt.Color(255, 255, 255));
        Starred_Activities.setRowHeight(30);
        Starred_Activities.setRowMargin(10);
        Starred_Activities.setSelectionBackground(new java.awt.Color(204, 204, 204));
        Starred_Activities.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        Starred_Activities.setShowHorizontalLines(false);
        Starred_Activities.setShowVerticalLines(false);
        Starred_Activities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Starred_ActivitiesMouseClicked(evt);
            }
        });
        Starred_Activities.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Starred_ActivitiesKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Starred_Activities);

        jLabel34.setForeground(new java.awt.Color(102, 102, 102));
        jLabel34.setText("Created and powered by: Faithtotwer media-teck                          Copyright@2018                                     faithtowermediateck@gmail.com");

        javax.swing.GroupLayout Starred_Activites_PageLayout = new javax.swing.GroupLayout(Starred_Activites_Page);
        Starred_Activites_Page.setLayout(Starred_Activites_PageLayout);
        Starred_Activites_PageLayout.setHorizontalGroup(
            Starred_Activites_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Starred_Activites_PageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Starred_Activites_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Starred_Activites_PageLayout.createSequentialGroup()
                        .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(editAct, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(StarAct, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeFromStarredBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        Starred_Activites_PageLayout.setVerticalGroup(
            Starred_Activites_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Starred_Activites_PageLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(Starred_Activites_PageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(searchField2)
                    .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editAct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StarAct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(removeFromStarredBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ParentPanel.add(Starred_Activites_Page, "card5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("calendar.png")));
    }
    
    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        AddNewPanel.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void hideTablesColumns(){
        AllActivity_Table.getColumnModel().getColumn(0).setMinWidth(0);
        AllActivity_Table.getColumnModel().getColumn(0).setMaxWidth(0);
        AllActivity_Table.getColumnModel().getColumn(0).setWidth(0);
        
        Starred_Activities.getColumnModel().getColumn(0).setMinWidth(0);
        Starred_Activities.getColumnModel().getColumn(0).setMaxWidth(0);
        Starred_Activities.getColumnModel().getColumn(0).setWidth(0);
    }
    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        AddNewPanel.setBackground(new Color(51,51,255));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       GotoAddNewActivityPanel();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GotoHomePanel();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GotoMyActivityPanel();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       GotoAddNewActivityPanel();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        GotoHomePanel();
        clearFields();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        GotoMyActivityPanel();
        clearFields();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        GotoStarredPage();
        clearFields();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       GotoStarredPage();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         GotoStarredPage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
       if (IdLbl.getText().isEmpty()){
            if( ((JTextComponent)ActivityDate.getDateEditor().getUiComponent()).getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Please Date is Required");
       }
        else{ 
               
            if(ActivityVenue.getText().isEmpty() && !NoVenue.isSelected()){
                JOptionPane.showMessageDialog(null,"Set Venue or Check 'Does not require venue' to Ignore");
            }else{
           if((ActivityHr.getText().isEmpty() ||  ActivityMin.getText().isEmpty()) && !NoTime.isSelected()){
                JOptionPane.showMessageDialog(null,"Set Time or Check 'Does not require time' to Ignore");
              }
            else{
               InsertData();
           }
           
            }    
        }
            
       }//End of if Label is Empty
       else{
           updateData();
       }
        
     
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void AMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMActionPerformed
         if(PM.isSelected()){  
            PM.setSelected(false);
            }else{
             AM.setSelected(true);
         }
         
    }//GEN-LAST:event_AMActionPerformed

    private void InsertData(){
        Queries Insert=new Queries();
        Insert.InsertActivity(ActivityName, ActivityDate, ActivityVenue, ActivityHr, ActivityMin, AM, PM, Star);
       
        Queries GetAll=new Queries();
        GetAll.GetAllActivities(AllActivity_Table);
        
        Queries getStarred=new Queries();
        getStarred.GetStarredActivities(Starred_Activities);
        
        hideTablesColumns();
    }
    private void PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMActionPerformed
        if(AM.isSelected()){
                AM.setSelected(false);
            }else{
                PM.setSelected(true);
            }
    }//GEN-LAST:event_PMActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        GotoHomePanel();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        GotoAddNewActivityPanel();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        GotoMyActivityPanel();
    }//GEN-LAST:event_jButton16ActionPerformed

    private void ActivityNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActivityNameKeyReleased
        CheckField();
    }//GEN-LAST:event_ActivityNameKeyReleased

    private void ActivityDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActivityDateKeyReleased
        CheckField();
    }//GEN-LAST:event_ActivityDateKeyReleased

    private void ActivityVenueKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActivityVenueKeyReleased
        CheckField();
    }//GEN-LAST:event_ActivityVenueKeyReleased
    private void AM_PM(){
        AM.setSelected(false);
        PM.setSelected(true);
    }
    private void ActivityHrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActivityHrKeyReleased
        try{
        int timeHrVal=Integer.parseInt(ActivityHr.getText());
        if(timeHrVal > 12){
            if(timeHrVal == 13){
                ActivityHr.setText(""+1);
            }else if(timeHrVal == 14){
                ActivityHr.setText(""+2);
            }else if(timeHrVal == 15){
                ActivityHr.setText(""+3);;
            }else if(timeHrVal == 16){
                ActivityHr.setText(""+4);
            }else if(timeHrVal == 17){
                ActivityHr.setText(""+5);
            }else if(timeHrVal == 18){
                ActivityHr.setText(""+6);
            }else if(timeHrVal == 19){
                ActivityHr.setText(""+7);
            }else if(timeHrVal == 20){
                ActivityHr.setText(""+8);
            }else if(timeHrVal == 21){
                ActivityHr.setText(""+9);
            }else if(timeHrVal == 22){
                ActivityHr.setText(""+10);
            }else if(timeHrVal == 23){
                ActivityHr.setText(""+11);
            }else if(timeHrVal >= 24){
                ActivityHr.setText(""+12);
            }
        
            AM_PM();
        }else if( timeHrVal < 1 ){ActivityHr.setText(""+1);}  
        
        }catch(Exception ex){}

        CheckField();
    }//GEN-LAST:event_ActivityHrKeyReleased

    private void ActivityMinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActivityMinKeyReleased
        try{
        int timeMinVal=Integer.parseInt(ActivityMin.getText());
        
        if( (timeMinVal >= 60) || (timeMinVal < 0)){
            ActivityMin.setText("00");
        }
        
        }catch(Exception ex){}
        
        CheckField();
    }//GEN-LAST:event_ActivityMinKeyReleased

    private void ActivityDateMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActivityDateMouseReleased
       CheckField();
    }//GEN-LAST:event_ActivityDateMouseReleased

    private void ActivityDateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActivityDateMousePressed
        CheckField();
    }//GEN-LAST:event_ActivityDateMousePressed

    private void ActivityDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ActivityDateMouseClicked
        CheckField();
    }//GEN-LAST:event_ActivityDateMouseClicked

    private void NoTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoTimeActionPerformed
        if (NoTime.isSelected()){
            ActivityHr.setForeground(new Color(240,240,240));
            ActivityHr.setText("Not set");
            ActivityMin.setText("");
            ActivityHr.setEditable(false);
            ActivityMin.setEditable(false);
            AM.setSelected(false);
            PM.setSelected(false);
            AM.setEnabled(false);
            PM.setEnabled(false);
            
            
        }else{
            ActivityHr.setForeground(new Color(0,0,0));
            ActivityHr.setText("");
            ActivityMin.setText("");
            ActivityHr.setEditable(true);
            ActivityMin.setEditable(true);
            AM.setSelected(true);
            AM.setEnabled(true);
            PM.setEnabled(true);
        }
        
        CheckField();
    }//GEN-LAST:event_NoTimeActionPerformed

    private void NoVenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoVenueActionPerformed
        if (NoVenue.isSelected()){
            ActivityVenue.setForeground(new Color(240,240,240));
            ActivityVenue.setText("Not required");
            ActivityVenue.setEditable(false);
        }else{
            ActivityVenue.setForeground(new Color(0,0,0));
            ActivityVenue.setText("");
            ActivityVenue.setEditable(true);
        }
        CheckField();
    }//GEN-LAST:event_NoVenueActionPerformed

    private void ActivityDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_ActivityDatePropertyChange
        CheckField();
    }//GEN-LAST:event_ActivityDatePropertyChange
    
    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        if(AllActivity_Table.getSelectionModel().isSelectionEmpty()){
            DeleteBtn.setEnabled(false);
        }
        else{DeleteActivity();DeleteBtn.setEnabled(false);}
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(AllActivity_Table.getSelectionModel().isSelectionEmpty()){
            DeleteBtn.setEnabled(false);
    }else{DeleteBtn.setEnabled(true);}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void AllActivity_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllActivity_TableMouseClicked
        TableAction();
    }//GEN-LAST:event_AllActivity_TableMouseClicked

    private void AllActivity_TableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AllActivity_TableKeyReleased
        TableAction();
    }//GEN-LAST:event_AllActivity_TableKeyReleased

    private void starActivityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starActivityBtnActionPerformed
        if(AllActivity_Table.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "No activity is selected");
        }
        else{
        
            Queries star=new Queries();
            star.updateStarred(AllActivity_Table);
            starActivityBtn.setEnabled(false);

            //Load Activities again(refresh table)
            Queries newLoad=new Queries();
            newLoad.GetAllActivities(AllActivity_Table);

            //Load Starred Messages(Refresh Table)
            Queries newStarred=new Queries();
            newStarred.GetStarredActivities(Starred_Activities);
            starActivityBtn.setEnabled(false);
            DeleteBtn.setEnabled(false);
            editActivityBtn.setEnabled(false);
        }
        hideTablesColumns();
    }//GEN-LAST:event_starActivityBtnActionPerformed

    private void editActivityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActivityBtnActionPerformed

        if(AllActivity_Table.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "No activity is selected");
        }
        else{
            int row=AllActivity_Table.getSelectedRow();
            String id = (AllActivity_Table.getModel().getValueAt(row, 0).toString());
            String A_name = (AllActivity_Table.getModel().getValueAt(row, 1).toString());
            String A_date = (AllActivity_Table.getModel().getValueAt(row, 2).toString());
            String A_venue = (AllActivity_Table.getModel().getValueAt(row, 3).toString());
            String A_time = (AllActivity_Table.getModel().getValueAt(row, 4).toString());
            
            
        IdLbl.setText(id);
        ActivityName.setText(A_name);
       ((JTextComponent)ActivityDate.getDateEditor().getUiComponent()).setText(A_date);
       ActivityVenue.setText(A_venue);
       
       GotoAddNewActivityPanel();
        }
    }//GEN-LAST:event_editActivityBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        clearFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void ActivityMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActivityMinKeyTyped
        if( ActivityMin.getText().length() == 2 && !(evt.getKeyChar()== KeyEvent.VK_DELETE || evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
         } OnlyDigits(evt);
    }//GEN-LAST:event_ActivityMinKeyTyped

    private void editActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActActionPerformed
        
        
        if(Starred_Activities.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "No activity is selected");
        }
        else{
            int row=Starred_Activities.getSelectedRow();
            String id = (Starred_Activities.getModel().getValueAt(row, 0).toString());
            String A_name = (Starred_Activities.getModel().getValueAt(row, 1).toString());
            String A_date = (Starred_Activities.getModel().getValueAt(row, 2).toString());
            String A_venue = (Starred_Activities.getModel().getValueAt(row, 3).toString());
            
        IdLbl.setText(id);
        ActivityName.setText(A_name);
        ((JTextComponent)ActivityDate.getDateEditor().getUiComponent()).setText(A_date);
        ActivityVenue.setText(A_venue);
       
        GotoAddNewActivityPanel();
       
        }
        
        hideTablesColumns();
    }//GEN-LAST:event_editActActionPerformed

    private void removeFromStarredBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFromStarredBtnActionPerformed
        if(Starred_Activities.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "No activity is selected");
        }
        else{
        
        Queries removeStarred=new Queries();
        removeStarred.removeStarred(Starred_Activities);
        
        //Load Activities again(refresh table)
        Queries newLoad=new Queries();
        newLoad.GetAllActivities(AllActivity_Table);

        //Load Starred activities(Refresh Table)
        Queries newStarred=new Queries();
        newStarred.GetStarredActivities(Starred_Activities);
        removeFromStarredBtn.setEnabled(false);
        editAct.setEnabled(false);
        }
        hideTablesColumns();
    }//GEN-LAST:event_removeFromStarredBtnActionPerformed

    private void Starred_ActivitiesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Starred_ActivitiesKeyReleased
        if(Starred_Activities.getSelectionModel().isSelectionEmpty()){
        }
        else{
            editAct.setEnabled(true);
            removeFromStarredBtn.setEnabled(true);
        }
    }//GEN-LAST:event_Starred_ActivitiesKeyReleased

    private void Starred_ActivitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Starred_ActivitiesMouseClicked
        if(Starred_Activities.getSelectionModel().isSelectionEmpty()){
        }
        else{
            editAct.setEnabled(true);
            removeFromStarredBtn.setEnabled(true);
        }
    }//GEN-LAST:event_Starred_ActivitiesMouseClicked

    private void searchField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchField1KeyReleased
        Queries searchQuery=new Queries();
        searchQuery.searchActivity(searchField1, AllActivity_Table);
        
        hideTablesColumns();
    }//GEN-LAST:event_searchField1KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        readMeDialog.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        readMeDialog.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        readMeDialog.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        readMeDialog.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void searchField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchField2KeyReleased
        Queries searchQuery=new Queries();
        searchQuery.searchStarredActivity(searchField2, Starred_Activities);
        
        hideTablesColumns();
    }//GEN-LAST:event_searchField2KeyReleased

    private void ActivityHrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ActivityHrKeyTyped
        if( ActivityHr.getText().length() == 2 && !(evt.getKeyChar()== KeyEvent.VK_DELETE || evt.getKeyChar()== KeyEvent.VK_BACK_SPACE)) {
            getToolkit().beep();
            evt.consume();
         }
        OnlyDigits(evt);
    }//GEN-LAST:event_ActivityHrKeyTyped

    //ALL CUSTOM METHODS
        private void CenterOnScreen(final Component C, final boolean absolute ){
            try{
                final int width=C.getWidth();
                final int height=C.getHeight();
                final Dimension screenSize=Toolkit.getDefaultToolkit().getScreenSize();
                int X=(screenSize.width / 2)-(width / 2);
                int Y=(screenSize.height / 2)-(height / 2);
                if(!absolute){
                    X /=2;
                    Y /=2;   
                }
                C.setLocation(X, Y);
            }catch(Exception ex){

            }  
    }
        private void SetDefaultSize(){
            this.setMinimumSize(new Dimension(720,730));
            this.setSize(new Dimension(730,720));
            
            readMeDialog.setMinimumSize(new Dimension(670,620));
            readMeDialog.setSize(new Dimension(670,590));
        }
        private void GotoMyActivityPanel(){
            ParentPanel.removeAll();
            ParentPanel.add(MyActivityPanel);
            ParentPanel.repaint();
            ParentPanel.revalidate();
            
            hideTablesColumns();
        }
        private void GotoAddNewActivityPanel(){
            ParentPanel.removeAll();
            ParentPanel.add(EnterActivity_Page);
            ParentPanel.repaint();
            ParentPanel.revalidate();
            
            hideTablesColumns();
        }
        private void GotoHomePanel(){
            ParentPanel.removeAll();
            ParentPanel.add(AddNew_Page);
            ParentPanel.repaint();
            ParentPanel.revalidate();
            
            hideTablesColumns();
        }
        private void GotoStarredPage(){
            ParentPanel.removeAll();
            ParentPanel.add(Starred_Activites_Page);
            ParentPanel.repaint();
            ParentPanel.revalidate();
            
            hideTablesColumns();
        }
        private void CheckField(){
            String A_Date=((JTextComponent)ActivityDate.getDateEditor().getUiComponent()).getText();
            
            if(ActivityName.getText().isEmpty()){
                SaveBtn.setEnabled(false);
            }else if(A_Date.isEmpty()){SaveBtn.setEnabled(false);}
            else if(ActivityVenue.getText().isEmpty()){    
                if(NoVenue.isSelected()==true){
                    SaveBtn.setEnabled(true);
                }
                else{ 
                    SaveBtn.setEnabled(false);
                }
            }
            else if(ActivityHr.getText().isEmpty()){
                
                if(NoTime.isSelected()){
                    SaveBtn.setEnabled(true);
                }else{ 
                    SaveBtn.setEnabled(false);
                }
                
            }else if(ActivityMin.getText().isEmpty()){
                if(NoTime.isSelected()){
                    SaveBtn.setEnabled(true);
                }else{ SaveBtn.setEnabled(false);}
            }
            else{
                SaveBtn.setEnabled(true);
            }
            
        }
        private void DeleteActivity(){
            if(AllActivity_Table.getSelectionModel().isSelectionEmpty()){
                JOptionPane.showMessageDialog(null, "Select Activity to remove");
            }else{
                int confirmagain = JOptionPane.showConfirmDialog(null, "<html>Are you sure You want remove?</html>", "Remove activity", JOptionPane.YES_NO_OPTION);
                if (confirmagain == 0) {
                    Queries delete=new Queries();
                    delete.DeleteActivity(AllActivity_Table);
                    
                    //Load Activities again(refresh table)
                    Queries newLoad=new Queries();
                    newLoad.GetAllActivities(AllActivity_Table);
                    
                    //Load Starred Messages(Refresh Table)
                    Queries newStarred=new Queries();
                    newStarred.GetStarredActivities(Starred_Activities);
                    
                    hideTablesColumns();
                }
            }   
        }
        private void TableAction(){
            if(AllActivity_Table.getSelectionModel().isSelectionEmpty()){
            }
            else{

                Queries checkStarred=new Queries();
                checkStarred.CheckifStarred(AllActivity_Table, starActivityBtn);
                editActivityBtn.setEnabled(true);
                DeleteBtn.setEnabled(true);
                hideTablesColumns();
            }
        }
        private void updateData(){
        Queries update=new Queries();
        update.UpdateActivity(ActivityName, ActivityDate, ActivityVenue, ActivityHr, ActivityMin, AM, PM, Star, IdLbl);
       
        Queries GetAll=new Queries();
        GetAll.GetAllActivities(AllActivity_Table);
        
        Queries getStarred=new Queries();
        getStarred.GetStarredActivities(Starred_Activities);
        
        hideTablesColumns();
    }
        private void clearFields(){
            IdLbl.setText("");
            ActivityName.setText("");
            ((JTextComponent)ActivityDate.getDateEditor().getUiComponent()).setText("");
            ActivityVenue.setText("");
            NoVenue.setSelected(false);
            NoTime.setSelected(false);
            AM.setEnabled(true);
            PM.setEnabled(true);
            AM.setSelected(true);
            PM.setSelected(false);
            ActivityHr.setText("");
            ActivityMin.setText("");
            Star.setSelected(false);
            SaveBtn.setEnabled(false);
        }
        
        private void OnlyDigits(java.awt.event.KeyEvent evt) {
            char enter = evt.getKeyChar();
            if (!(Character.isDigit(enter) || (enter == com.sun.glass.events.KeyEvent.VK_BACKSPACE) || (enter == com.sun.glass.events.KeyEvent.VK_DELETE))) {
                evt.consume();
                getToolkit().beep();

            }
        }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AM;
    private com.toedter.calendar.JDateChooser ActivityDate;
    private javax.swing.JTextField ActivityHr;
    private javax.swing.JTextField ActivityMin;
    private javax.swing.JTextField ActivityName;
    private javax.swing.JTextField ActivityVenue;
    private javax.swing.JPanel AddNewPanel;
    private javax.swing.JPanel AddNew_Page;
    private javax.swing.JTable AllActivity_Table;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JPanel EnterActivity_Page;
    private javax.swing.JLabel IdLbl;
    private javax.swing.JPanel MyActivityPanel;
    private javax.swing.JCheckBox NoTime;
    private javax.swing.JCheckBox NoVenue;
    private javax.swing.JCheckBox PM;
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JRadioButton Star;
    private javax.swing.JButton StarAct;
    private javax.swing.JPanel Starred_Activites_Page;
    private javax.swing.JTable Starred_Activities;
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel date;
    private javax.swing.JButton editAct;
    private javax.swing.JButton editActivityBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog readMeDialog;
    private javax.swing.JButton removeFromStarredBtn;
    private javax.swing.JTextField searchField1;
    private javax.swing.JTextField searchField2;
    private javax.swing.JButton starActivityBtn;
    // End of variables declaration//GEN-END:variables

}
